logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    com:
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8989
spring:
  application:
    name: registry-srv
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false