logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    com:
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8989
spring:
  application:
    name: registry-srv
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enableSelfPreservation: false  # 关闭自我保护机制，在自我保护机制下，服务列表不会剔除无效服务
    eviction-interval-timer-in-ms: 3000  # 失效服务主动下线