configserver-name: localhost
mysqlserver-name: localhost
server:
  port: 8888
logging:
   config: classpath:log4j2.xml
#  config: http://${configserver-name}:7777/user-srv/default/log4j2.xml?useDefaultLabel
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physicalStrategy: com.oyoungy.config.WallPhysicalTableNamingStrategy
    show-sql: true
  datasource:
    url: jdbc:mysql://${mysqlserver-name}:3306/universal-wall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC  # Asia/Shanghai
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      read-only: false
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  sql:
    init:
      mode: never
  jackson:
    time-zone: GMT+8
  allowOverride: true
  overrideNone: true
