logging:
  level:
    root: INFO
spring:
  application:
    name: posting-srv
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: '!ut'
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configserver

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8989/eureka/

---
spring:
  config:
    activate:
      on-profile: 'ut'
    import: 'optional:configserver:'
