configserver-name: localhost
mysqlserver-name: localhost
kafka-brokers: localhost:9094

server:
  port: 9999
logging:
  config: classpath:log4j2.xml
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physicalStrategy: com.oyoungy.config.WallPhysicalTableNamingStrategy
    show-sql: true
  datasource:
    url: jdbc:mysql://${mysqlserver-name}:3306/universal-wall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC  # Asia/Shanghai
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      read-only: false
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  sql:
    init:
      mode: never
  jackson:
    time-zone: GMT+8


  cloud:
    function:
      definition: approvedCategory;approvedPosting;approvingCategory;approvingPosting
    stream:
      defaultBinder: kafka
      instanceCount: 1
      instanceIndex: 0
      function:
        autodetect: false
        bindings:
          approvedCategory-in-0: category-a-event-in
          approvedPosting-in-0: posting-a-event-in
          approvingPosting-in-0: posting-event-in
          approvingCategory-in-0: category-event-in
      bindings:
        category-event-in:
          destination: category-topic
          group: logging
          consumer:
            partitioned: true
        category-a-event-in:
          destination: category-a-topic
          group: post-approved
          consumer:
            partitioned: true
        posting-event-in:
          destination: posting-topic
          group: logging
          consumer:
            partitioned: true
        posting-a-event-in:
          destination: posting-a-topic
          group: post-approved
          consumer:
            partitioned: true

        category-event-out:
          destination: category-topic
          producer:
            partitionCount: 2
        posting-event-out:
          destination: posting-topic
          producer:
            partitionCount: 2

      kafka:
        binder:
          brokers: ${kafka-brokers}
          autoCreateTopics: true
          autoAddPartitions: true
