version: '2'
services:
  eurekaserver:
    image:   oyoungy/wall-proj:registry
#    ports:
#      - "8989:8989"
    environment:
      EUREKASERVER_PORT: "8989"
  configserver:
    image: oyoungy/wall-proj:confsrv
#    ports:
#      - "7777:7777"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
      ENCRYPT_KEY:       "IMSYMMETRIC"
#      EUREKASERVER:       "host.docker.internal"
      EUREKASERVER:       "eurekaserver"
    volumes:
      - type: volume
        source: configserver-properties
        target: /usr/local/wall/configserver/mount
  geteway:
    image: oyoungy/wall-proj:gateway
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
      EUREKASERVER: "eurekaserver"
      CONFIGSERVER: configserver
  userserver:
    image: oyoungy/wall-proj:user-srv
#    ports:
#      - "8888:8888"
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      EUREKASERVER:       "eurekaserver"
      DATABASESERVER: "host.docker.internal"
      CONFIGSERVER: configserver
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181

  kafka1:
    image: bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka_cluster1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181

volumes:
  configserver-properties:
    external: true

networks:
  default:
    name: my-wall-net
    external: true
