version: '2'
include:
  - event-services.yaml
services:
  eurekaserver:
    restart: unless-stopped
    image:   oyoungy/wall-proj:registry
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS localhost:8989 || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    ports:
      - "8989:8989"
    environment:
      EUREKASERVER_PORT: "8989"
  configserver:
    image: oyoungy/wall-proj:confsrv
    restart: unless-stopped
    depends_on:
      - eurekaserver
    ports:
      - "7777:7777"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
#      EUREKASERVER:       "host.docker.internal"
      EUREKASERVER:       "eurekaserver"
    volumes:
      - configserver-properties:/usr/local/wall/mount
  geteway:
    image: oyoungy/wall-proj:gateway
    restart: unless-stopped
    depends_on:
      - eurekaserver
      - configserver
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
      EUREKASERVER: "eurekaserver"
      CONFIGSERVER: configserver
  userserver:
    image: oyoungy/wall-proj:user-srv
    restart: no
    depends_on:
      - eurekaserver
      - configserver
#    ports:
#      - "8888:8888"
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
      EUREKASERVER:       "eurekaserver"
      DATABASESERVER: "host.docker.internal"
      CONFIGSERVER: configserver

  postingserver:
    image: oyoungy/wall-proj:posting-srv
    restart: no
    depends_on:
      - eurekaserver
      - configserver
      - zoo1
    ports:
      - "9999:9999"
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekaserver:8989/eureka/"
      EUREKASERVER_PORT: "8989"
      EUREKASERVER: "eurekaserver"
      DATABASESERVER: "host.docker.internal"
      CONFIGSERVER: configserver
#      KAFKABROKERS: "kafka1:9092;kafka2:9092;kafka3:9092"
      KAFKABROKERS: "kafka1-dev:9092"

volumes:
  configserver-properties:
    external: true

#networks:
#  default:
#    name: my-wall-net
#    external: true
