server:
  port: 7777
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - file:///H:/MY_OWN_CODE_FILE/universal-wall-refactor/others/config/{application}
            - file:/usr/local/wall/mount/config/{application}
  application:
    name: configserver

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8989/eureka/
